### ISSUE TITLE
Mochi Live TV: unable to install on Hisense Google TV (Android TV OS 11)

### ISSUE THREAD

**Issue by jhedfors** [brunochanrio/MochiTIF#2]
I am not able to complete setup {app crashing) of Mochi Live TV on my Hisense TV (Google TV - Android  TV OS 11).  I am able to install Live Channels on Hisense TV with no issues.

For comparison, I was able to install Mochi Live TV on Chromecast with Google TV (Android TV OS 12) without any issues.

**Comment by jhedfors** [comment]
@brunochanrio Anything you need from me to help resolve this issue?

**Comment by brunochanrio** [comment]
> @brunochanrio Anything you need from me to help resolve this issue?

Try the new Mochi Live TV update, the 1.0.6, released today, includes bug fixes, possibly fixes the Hisense bug

**Comment by jhedfors** [comment]
I did manage to get it set up on my Hisense TV - Thank you!

The app crashes however every time I go to a Sample Rich Input channel which automatically gets installed (am pretty sure this was optional when I installed this Mochi Live TV on my CCwGTV). It also crashes when I try to deselect the channel from Customize channel list. I am assuming this must be video rendering issue.

**Comment by brunochanrio** [comment]
> I did manage to get it set up on my Hisense TV - Thank you!
> 
> The app crashes however every time I go to a Sample Rich Input channel which automatically gets installed (am pretty sure this was optional when I installed this Mochi Live TV on my CCwGTV). It also crashes when I try to deselect the channel from Customize channel list. I am assuming this must be video rendering issue.

Is the Sample TV Input the cause of the issue, i'm planning to consider replace it with a totally-new Sample TV Input based on M3U, and adding a M3U TV Input Service to add Channels from a M3U list, and with EPG

**Comment by jhedfors** [comment]
> Is the Sample TV Input the cause of the issue, i'm planning to consider replace it with a totally-new Sample TV Input based on M3U, and adding a M3U TV Input Service to add Channels from a M3U list, and with EPG

Yes - Whenever the app tries to render the video in the Sample Rich Input category, it crashes. I only got it to work by being very quick to disable the channel group (as it is enabled by default). Even now, when I scroll through the Customize channel list, as soon as I reach one of those channels, it tries to preview the channel for a moment then crashes the app.

Side note: I am using the app "PVR Live" to bring in my M3U lists, but I am curious about your built-in offering.

**Comment by brunochanrio** [comment]
I discovered the bug, is a MochiTIF library bug, specifically in the
EpgSyncJobService class, and are caused by JUnit Assert, i'll remove the
Assert code in the EpgSyncJobService in a future release of MochiTIF
library to fix the bug

**Comment by jhedfors** [comment]
@brunochanrio With the Nov 11th updatate I see that it no longer crashes when I view the Sample Rich Input channels on my Hisense Google TV. Thanks!
